### ISSUE TITLE
Implicit wait timeouts with Firefox 55

### ISSUE THREAD

**Issue by epoxa** [giorgiosironi/phpunit-selenium#414]
Hi all,
Calling 
`$this->timeouts()->implicitWait(5000);`
leads to error:
```
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: POST /session/76d6c302-bafc-4a65-ac20-a8ddd453b2a7/timeouts/implicit_wait did not match a known command
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'HP', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_111'
Driver info: driver.version: unknown

```
Firefox 55. geckodriver 0.18.0
How can I set timeouts othwer way? Thanks

**Comment by giorgiosironi** [comment]
This looks like a problem with the Firefox version or driver? The API to use is taken from https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtimeoutsimplicit_wait

**Comment by ankitjain28may** [comment]
@giorgiosironi Any other way to solve this issue ?

**Comment by epoxa** [comment]
@ankitjain28may Did you get the similar issue with Firefox?
I fear the link mentioned by @giorgiosironi is outdated. It marked as "Status: OBSOLETE See current W3C specification for WebDriver".
Is it possible that latest FF driver changed implicit waits behavior?
Btw the same configuration works perfect with Chrome driver. And all other methods of FF driver I used  are works perfect either.

**Comment by ankitjain28may** [comment]
@epoxa Yes, I am getting the same problem in Firefox (v 55.0)

**Comment by eugeniominissale** [comment]
I'm facing the same problem with Firefox 56, Mac OS X 10.12 and selenium-server-standalone-3.6.0.jar with Python.

**Comment by kolesar-andras** [comment]
Same problem here with Firefox 56 on Ubuntu, geckodriver 0.19.0, PHPUnit 5.7.22. Chrome works fine.

```
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: POST /session/2636302c-618e-4646-b168-8e0101ffdd93/timeouts/implicit_wait did not match a known command
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'kolesar', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-92-generic', java.version: '1.8.0_131'
Driver info: driver.version: unknown
```

**Comment by epoxa** [comment]
Try this workaround:
`        $this->__call('timeouts', [
            'pageLoad' => 5000,
            'script'=> 5000,
            'implicit' => 5000,
        ]);
`

**Comment by gohelkiran** [comment]
same issue with v3.12.0 standalone server and latest geckodriver v0.20.1

 Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownCommandException' with message 'POST /session/27022282-a690-4626-87a3-948dc8b9510e/timeouts/implicit_wait did not match a known command Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z' System info: host: 'WIN-SR99V6JM70G', ip: '10.0.0.249', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_171' Driver info: driver.version: unknown' in E:\webenvoy\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:106 Stack trace: #0 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(9, 'POST /session/2...', Array) #1 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(535): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\RemoteExecuteMethod.php(40): Facebook\WebDriver in E:\webenvoy\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 106

**Comment by IAmJahoo** [comment]
Hi, everyone.

Did anyone find solution to this issue? I had a lot of problems with that as well, I finally managed to run standalone server v 3.4.0 with geckodriver0.21 and it runs well, but with newer i always have error :
`Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownCommandException' with message 'POST /session/{{session_UUID}}/timeouts/implicit_wait did not match a known command`

**Comment by meshfields** [comment]
Same issue
